version: '2'

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    image: cllu/docker-demo
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: redis:3.2.0
    command: redis-server --appendonly yes
