version: '2'

services:
  lb:
    build:
      context: .
      dockerfile: docker/load_balancer/Dockerfile
    image: cllu/demo-load_balancer
    container_name: lb
    ports:
      - "80:80"
    environment:
      - constraint:node==master
      - APP_NAME=docer-demo
      - CONSUL_URL=${KV_IP}:8500
    depends_on:
      - app
    networks:
      - front-tier

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    image: cllu/demo-app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - front-tier
      - back-tier

  redis:
    image: redis:3.2.0
    container_name: redis
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - back-tier

volumes:
  redis-data:
    driver: local

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge
