version: '2'

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    image: cllu/docker-demo
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - front
      - back

  redis:
    image: redis:3.2.0
    container_name: redis
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - back

volumes:
  redis-data:
    driver: local

networks:
  front:
    driver: bridge
  back:
    driver: bridge
